import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "@/app/[locale]/globals.css";
import { NextIntlClientProvider } from "next-intl";
import { ToastProvider } from "@/app/_context/ToastProvider";

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html
            lang="en"
            className={`${roboto.variable} ${roboto.variable} h-full antialiased`}
        >
            <body className="min-h-full flex flex-col">
                <NextIntlClientProvider>
                    <ToastProvider>{children}</ToastProvider>
                </NextIntlClientProvider>
            </body>
        </html>
    );
}
